# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - azure-pipelines-arm.yml
    - ARM

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Revision: $[counter(variables['Minor'], 1)]

name: $(major).$(minor).$(Revision)

resources:
    repositories:
        - repository: iot
          type: git
          name: precision-lubrication/Railwayrobotics.iot

stages:
- stage: Test
  displayName: Unit test modules
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: test
    displayName: Unit test modules
    steps:
    - task: DotNetCoreCLI@2
      displayName: DotNet Restore
      inputs:
        command: 'restore'
        projects: '**/*UnitTests.csproj'

    - task: DotNetCoreCLI@2
      enabled: false
      displayName: 'UT: Railwayrobotics.Applesprayer.Brain.UnitTests'
      inputs:
        command: test
        projects: '**/Railwayrobotics.Applesprayer.Brain.UnitTests.csproj'
        arguments: '--configuration $(buildConfiguration)'

- stage: GpioEdge
  displayName: Build target arm64v8 
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: tar
    displayName: Build docker tar arm64v8
    steps:
    - bash: |
       sudo apt-get update
       sudo apt-get install -y qemu qemu-user-static qemu-user binfmt-support   
       cp /usr/bin/qemu-aarch64-static $sourcedir

      displayName: 'Install QEMU'
      env:
        sourcedir: $(Build.SourcesDirectory)/Railwayrobotics.Applesprayer.Gpio
    
    - task: Docker@2
      displayName: 'Run privileged container'
      inputs:
        command: run
        arguments: '--rm --privileged multiarch/qemu-user-static:register --reset'
      enabled: true

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker run --rm --privileged multiarch/qemu-user-static:register --reset'
    
    - template: docker_save_tar.yml@iot
      parameters:
        dockerFile: $(Build.SourcesDirectory)/Railwayrobotics.Applesprayer.Gpio/Dockerfile.arm64v8
        context: $(Build.SourcesDirectory)/Railwayrobotics.Applesprayer.Gpio
        tag: rr-applesprayer-gpio:$(Build.BuildNumber)
        outputFile: $(Build.ArtifactStagingDirectory)/rr-applesprayer-gpio.tar
    - task: PublishBuildArtifacts@1

- stage: Edge
  displayName: Build target arm64v8 
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: tar
    displayName: Build docker tar arm64v8
    steps:
    - template: docker_save_tar.yml@iot
      parameters:
        dockerFile: $(Build.SourcesDirectory)/Railwayrobotics.Applesprayer.Brain/Dockerfile.arm64v8
        context: $(Build.SourcesDirectory)
        tag: rr-applesprayer-brain:$(Build.BuildNumber)
        outputFile: $(Build.ArtifactStagingDirectory)/rr-applesprayer-brain.tar

    - task: Bash@3
      displayName: Install iotedgedev
      inputs:
        targetType: 'inline'
        script: 'pip install -U iotedgedev'
    - task: AzureIoTEdge@2
      displayName: Generate deployment manifest dev
      inputs:
        action: 'Generate deployment manifest'
        templateFilePath: 'deployment.template.dev.json'
        defaultPlatform: 'arm64v8'
        deploymentManifestOutputPath: '$(Build.ArtifactStagingDirectory)/config/dev/deployment.dev.json'
        validateGeneratedDeploymentManifest: 'true'
      env:
        CONTAINER_REGISTRY_SERVER: railwayroboticsdev.azurecr.io
        ACR_ID: railwayroboticsdev

    - task: AzureIoTEdge@2
      displayName: Generate deployment manifest prototype
      inputs:
        action: 'Generate deployment manifest'
        templateFilePath: 'deployment.template.prototype.json'
        defaultPlatform: 'arm64v8'
        deploymentManifestOutputPath: '$(Build.ArtifactStagingDirectory)/config/dev/deployment.prototype.json'
        validateGeneratedDeploymentManifest: 'true'
      env:
        CONTAINER_REGISTRY_SERVER: railwayroboticsdev.azurecr.io
        ACR_ID: railwayroboticsdev

 #   - task: AzureIoTEdge@2
 #     displayName: Generate deployment manifest
 #     inputs:
 #       action: 'Generate deployment manifest'
 #       templateFilePath: 'deployment.template.json'
 #       defaultPlatform: 'arm32v7'
 #       deploymentManifestOutputPath: '$(Build.ArtifactStagingDirectory)/config/prod/deployment.json'
 #       validateGeneratedDeploymentManifest: 'true'
 #     env:
 #       CONTAINER_REGISTRY_SERVER: ??.azurecr.io
 #       ACR_ID: ??
        
    - task: PublishBuildArtifacts@1
