FROM arm64v8/python:3.7.6-buster

WORKDIR /app
COPY /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static 

COPY requirements.txt ./
RUN pip install -r requirements.txt

RUN rm -f /usr/bin/qemu-arm-static 

COPY . .

RUN chmod +rwx main.py

CMD [ "python3", "-u", "./main.py" ]