#!/usr/bin/env python3.7

FROM --platform=linux/arm64 debian:stretch-slim
FROM arm64v8/python:3.7.6-buster

WORKDIR /app

COPY requirements.txt ./
COPY prereqs.sh ./

RUN chmod prereqs.sh
RUN /prereqs.sh

COPY . .

RUN chmod +rwx main.py

CMD [ "python3", "-u", "./main.py" ]